# Generated by Django 5.1.4 on 2025-01-15 07:10

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Rate', models.FloatField(max_length=11)),
                ('Uuid', models.UUIDField(default=uuid.uuid4)),
                ('File', models.FileField(upload_to='video')),
                ('Image', models.ImageField(upload_to='img')),
                ('Poster', models.ImageField(upload_to='poster')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='Duration in HH:MM format.')),
                ('uploaded_date', models.DateField(default=datetime.date.today)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movieapp.genre')),
            ],
        ),
    ]
