# Generated by Django 5.1.4 on 2025-03-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='popularity_score',
        ),
    ]
