# Generated by Django 5.1.4 on 2025-03-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_remove_movies_genre_movies_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='genrez',
        ),
    ]
