# Generated by Django 5.1.4 on 2025-03-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_rename_genre_movies_genrez'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='is_upcoming',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='uploaded_date',
        ),
    ]
